chore: browser page() - optional 'name' and 'category' parameters
amplitude/itly-sdk pull request #110
Opened 2021-06-11 17:59 UTC by falconandy

2021-06-11 19:33 UTC, justin-fiedler requested changes
@falconandy change looks good but I would feel better with some tests. I'm thinking we could add a `browser.test.ts` and `node.test.ts` that would test the corresponding platform interfaces. Each could include a simple test for itly.page "category and name should be optional".
```
// browser.test.ts
expect(() => itly.page()).notToThrow()

// node.test.ts
expect(() => itly.page('user-id')).notToThrow()
```

2021-06-13 09:23 UTC, falconandy commented
@justin-fiedler 
The tests are added. Also I added node-specific Itly interface - with required `userId` parameter

2021-06-21 22:15 UTC, justin-fiedler commented
Thanks @falconandy the changes look great but I am holding off as a few customers have been using `anonymousId` and `deviceId` instead of `userId` in some cases. We may want to keep `userId` as `String | undefined` in Node to better support these usages. TBD.

2021-07-01 17:54 UTC, justin-fiedler approved these changes

2021-07-01 17:54 UTC, merged